# Generated by Django 3.0.2 on 2020-01-04 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password1',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password2',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
