# Generated by Django 3.0 on 2020-01-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userinfo_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_status',
            new_name='user_status_verified',
        ),
    ]
