# Generated by Django 3.0.2 on 2020-01-07 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200104_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
