# Generated by Django 3.0.2 on 2020-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200107_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roll_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
