# Generated by Django 3.0 on 2020-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200115_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_status_verified',
            field=models.BooleanField(default=False),
        ),
    ]
