# Generated by Django 3.0 on 2020-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200115_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_status_verified',
            field=models.CharField(max_length=10),
        ),
    ]
